### PR TITLE
Support Flow LRCN

### PR DESCRIPTION
**Pull request by LMdeLiangMi**
# Support Flow LRCN From Quadra_L
- [Quadra_L](http://www.swcontest.net/index.php?a=show&m=news&aid=177)
## Preparing
- install protocol buffer 3.4.0, referring this link http://blog.csdn.net/twilightdream/article/details/72953338
- sudo -H pip install --upgrade protobuf==3.1.0.post1

## Building
- remember WITH_PYTHON_LAYER := 1 !
- make all
- make pycaffe

## Training
- download data and models from http://www.eecs.berkeley.edu/~lisa_anne/LRCN_video
- change my path like '/home/link/frames' in sequence_input_layer.py to your path and modify other relative path
- bash run_singleFrame_flow.sh, run_lstm_flow.sh, start training!

### CODE REVIEW

**Comment by LMdeLiangMi** [comment]
@jczaja @ftian1

**Comment by hshen14** [comment]
Thanks for the PR. We will merge it soon.

**Comment by ftian1** [comment]
@LMdeLiangMi I have reviewed your PR, it's ok for me. I will follow our process to merge into intel caffe trunk. it's supposed to be seen at next release.

PS: I will move your changes in $CAFFE/README.md to examples/LRCN_activity_recognition/README.txt and I will remove some unnecessary blank line changes.

**Comment by ftian1** [comment]
@LMdeLiangMi , we have concern about the IP of examples/LRCN_activity_recognition/pyflow/createFlow.py you newly added. could you let me know where it comes from? is is authorized by original author?

**Comment by LMdeLiangMi** [comment]
I write the createFlow.py but I import the pyflow that is from https://github.com/pathak22/pyflow.
@ftian1

**Comment by LMdeLiangMi** [comment]
Should I remove it?

**Comment by ftian1** [comment]
I think it's more clear:)  thanks

**Comment by LMdeLiangMi** [comment]
Thank you very much!

**Comment by ftian1** [comment]
you will see it at next release

**Pull request closed without merging**
