### PR TITLE
Fix ReadImageToDatum to allow images with alpha channel

### PR DESCRIPTION
**Pull request by aprocter**
This is a fix for a bug in `ReadImageToDatum` which results in an uncaught OpenCV exception when loading images with an alpha channel. (This is rare in JPEGs, but we have actually encountered an example in the ILSVRC12 dataset, and the resulting exception crashes convert_imageset.sh when producing a JPEG-encoded LMDB.)

`ReadImageToDatum` seems to have been written on the assumption that anything that doesn't have three color channels is grayscale, and calls` cvtColor` with `COLOR_GRAY2BGR`. This assumption fails on BGRA images, which have four channels.

### CODE REVIEW

**Comment by aprocter** [comment]
Here's a test case. To run:

```
$ cd caffe
$ tar xvzf convert_imageset_bug.tar.gz
$ ./convert_imageset_bug.sh
```

[convert_imageset_bug.tar.gz](https://github.com/intel/caffe/files/731613/convert_imageset_bug.tar.gz)

**Comment by jczaja** [comment]
Thanks we will look to this very soon!

**Comment by aprocter** [comment]
@jczaja Looks like it's been merged in ea4405bbfdbd57a0187a09d53c6329791008b142?

**Comment by jczaja** [comment]
@aprocter You are right it is merged now. closing

**Pull request closed without merging**
